#!/usr/bin/python
 #################################
    #Name: Everlyne 
    #Date:
    #LOOPS
###################################    
#Creating loops
schools = ['Mercy' , 'Joy' , 'Peace' , 'Kindness']
students =['Nadia' , 'Raziel' , 'Selene' , 'Dominic' , 'Caitlin']
print(f"Hello I am {students[0]} and I study at school of {schools[0]} ")
print(f"Hello I am {students[1]} and I study at school of {schools[1]} ")
print(f"Hello I am {students[2]} and I study at school of {schools[2]} ")
print(f"Hello I am {students[3]} and I study at school of {schools[3]} ")

#for loops
for student in students:
    print(f'Hello I am {students}')
print("\t")
for school in schools:
    print(f'I attend the school of {schools}')

squares = []
for number in range(0,10):
    square = number **2
    squares.append (square)
print(squares)

cubes =[]
for number in range (0,10):
    cube = number **3
    cubes.append (cube)
print(cubes)

sum = 0
for number in range (0,10):
    sum = sum + number
print(sum)

sum = 0
for number in range (0,100):
    sum = sum + number
print(sum)





