print("Hello world")
print("My name is Everlyne")
print("I love movies")
print("I am 17 years old")
print("I am a good person")
print("I have 3 sisters")
print("I play volleyball")
print("I absolutely love movies")
print("I listen to a lot of music")
print("I want to live in Sydney, Australia one day")
print("My sister Yvonne is awesome!")
print("I will probably meet Vinnie Hacker one day.")